#!/usr/bin/env node
/* export-scene.mjs — static world → GLB + manifest for the offline light bake (tools/bake/bake.py). See BAKE.md.
 *
 *   node tools/bake/export-scene.mjs [--out tools/bake/out] [--terrain-res 1024] [--warm 22000] [--headful]
 *
 * Headless Chrome (puppeteer-core, system Chrome) opens open-world.html#dbg through the benchmark lock
 * (tools/.stand.lock), starts a new game, waits for the world to settle (packs, rock re-seat, snow drifts), injects
 * tools/bake/page-export.js and exports:
 *   <out>/scene.glb        every static object (world transforms; instanced sets as EXT_mesh_gpu_instancing),
 *                          lit albedo (colour × mean albedo-map), emissive, alpha-tested foliage with its PNG mask,
 *                          the terrain re-sampled from the rendered snow surface (COLOR_0 = albedo for the bounce),
 *                          KHR_lights_punctual: moon, aurora, static point lights; scene.extras.env = sky / fog / hemi.
 *   <out>/export.json      manifest: stable object ids, categories, bake mode per object, env, terrain grid, trees.
 * Node ids (node.extras.id) are the ids the runtime matches (BAKE.md §IDs).
 */
import fs from 'node:fs';
import path from 'node:path';
import { openWorld, GAME, sleep } from './lib.mjs';

const argv = process.argv.slice(2);
const opt = (k, d) => { const i = argv.indexOf('--' + k); return i >= 0 ? (argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : true) : d; };
const OUT = path.resolve(opt('out', path.join(GAME, 'tools', 'bake', 'out')));
fs.mkdirSync(OUT, { recursive: true });

/* ------------------------------------------------------------------ bake mode per object */
// object  : unique mesh → its own lightmap island in a per-site atlas (UV2 generated by bake.py)
// instanced: shared geometry drawn many times → object-space AO on UV2 (one small map per unique geometry)
// tree    : per-part crown AO + thickness in vertex colours
// none    : exported as occluder / bounce only
function bakeMode(o) {
  if (o.cat === 'backdrop' || o.cat === 'pickup') return 'none';
  if (o.instances) return o.count >= 2 ? 'instanced' : 'object';
  return 'object';
}

/* ------------------------------------------------------------------ math */
function decompose(m, o) {   // column-major 4×4 → t, r (quat xyzw), s
  let sx = Math.hypot(m[o], m[o + 1], m[o + 2]), sy = Math.hypot(m[o + 4], m[o + 5], m[o + 6]), sz = Math.hypot(m[o + 8], m[o + 9], m[o + 10]);
  const det = m[o] * (m[o + 5] * m[o + 10] - m[o + 6] * m[o + 9]) - m[o + 4] * (m[o + 1] * m[o + 10] - m[o + 2] * m[o + 9]) + m[o + 8] * (m[o + 1] * m[o + 6] - m[o + 2] * m[o + 5]);
  if (det < 0) sx = -sx;
  const r00 = m[o] / sx, r10 = m[o + 1] / sx, r20 = m[o + 2] / sx, r01 = m[o + 4] / sy, r11 = m[o + 5] / sy, r21 = m[o + 6] / sy, r02 = m[o + 8] / sz, r12 = m[o + 9] / sz, r22 = m[o + 10] / sz;
  const tr = r00 + r11 + r22; let x, y, z, w;
  if (tr > 0) { const s = 0.5 / Math.sqrt(tr + 1); w = 0.25 / s; x = (r21 - r12) * s; y = (r02 - r20) * s; z = (r10 - r01) * s; }
  else if (r00 > r11 && r00 > r22) { const s = 2 * Math.sqrt(1 + r00 - r11 - r22); w = (r21 - r12) / s; x = 0.25 * s; y = (r01 + r10) / s; z = (r02 + r20) / s; }
  else if (r11 > r22) { const s = 2 * Math.sqrt(1 + r11 - r00 - r22); w = (r02 - r20) / s; x = (r01 + r10) / s; y = 0.25 * s; z = (r12 + r21) / s; }
  else { const s = 2 * Math.sqrt(1 + r22 - r00 - r11); w = (r10 - r01) / s; x = (r02 + r20) / s; y = (r12 + r21) / s; z = 0.25 * s; }
  return { t: [m[o + 12], m[o + 13], m[o + 14]], r: [x, y, z, w], s: [sx, sy, sz] };
}
const fromB64 = (s, T) => { const b = Buffer.from(s, 'base64'); return new T(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength)); };

/* ------------------------------------------------------------------ GLB writer */
class GLB {
  constructor() { this.json = { asset: { version: '2.0', generator: 'tools/bake/export-scene.mjs' }, scene: 0, scenes: [{ nodes: [] }], nodes: [], meshes: [], materials: [], accessors: [], bufferViews: [], buffers: [], images: [], textures: [], samplers: [], extensionsUsed: [] }; this.chunks = []; this.len = 0; }
  view(buf, target) {
    const pad = (4 - (this.len % 4)) % 4; if (pad) { this.chunks.push(Buffer.alloc(pad)); this.len += pad; }
    const b = Buffer.from(buf.buffer, buf.byteOffset, buf.byteLength);
    this.json.bufferViews.push(Object.assign({ buffer: 0, byteOffset: this.len, byteLength: b.length }, target ? { target } : {}));
    this.chunks.push(b); this.len += b.length; return this.json.bufferViews.length - 1;
  }
  acc(arr, type, ct, target, minmax) {
    const n = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4 }[type], a = { bufferView: this.view(arr, target), componentType: ct, count: arr.length / n, type };
    if (minmax) { const mn = Array(n).fill(Infinity), mx = Array(n).fill(-Infinity); for (let i = 0; i < arr.length; i++) { const k = i % n; if (arr[i] < mn[k]) mn[k] = arr[i]; if (arr[i] > mx[k]) mx[k] = arr[i]; } a.min = mn; a.max = mx; }
    this.json.accessors.push(a); return this.json.accessors.length - 1;
  }
  ext(n) { if (!this.json.extensionsUsed.includes(n)) this.json.extensionsUsed.push(n); }
  write(file) {
    this.json.buffers = [{ byteLength: this.len }];
    for (const k of ['images', 'textures', 'samplers', 'extensionsUsed']) if (!this.json[k].length) delete this.json[k];
    let js = Buffer.from(JSON.stringify(this.json)); const jp = (4 - (js.length % 4)) % 4; js = Buffer.concat([js, Buffer.alloc(jp, 0x20)]);
    let bin = Buffer.concat(this.chunks); const bp = (4 - (bin.length % 4)) % 4; bin = Buffer.concat([bin, Buffer.alloc(bp)]);
    const h = Buffer.alloc(12); h.writeUInt32LE(0x46546c67, 0); h.writeUInt32LE(2, 4); h.writeUInt32LE(12 + 8 + js.length + 8 + bin.length, 8);
    const c0 = Buffer.alloc(8); c0.writeUInt32LE(js.length, 0); c0.writeUInt32LE(0x4e4f534a, 4);
    const c1 = Buffer.alloc(8); c1.writeUInt32LE(bin.length, 0); c1.writeUInt32LE(0x004e4942, 4);
    fs.writeFileSync(file, Buffer.concat([h, c0, js, c1, bin]));
  }
}

function buildGlb(X) {
  const G = new GLB(), J = G.json, F = 5126, U32 = 5125, ARR = 34962, IDX = 34963;
  // geometry accessors
  const geoAcc = X.geos.map((g) => {
    const P = fromB64(g.P, Float32Array), a = { POSITION: G.acc(P, 'VEC3', F, ARR, true) };
    if (g.N) a.NORMAL = G.acc(fromB64(g.N, Float32Array), 'VEC3', F, ARR);
    if (g.UV) a.TEXCOORD_0 = G.acc(fromB64(g.UV, Float32Array), 'VEC2', F, ARR);
    if (g.COL) a.COLOR_0 = G.acc(fromB64(g.COL, Float32Array), 'VEC3', F, ARR);
    return { attributes: a, indices: G.acc(fromB64(g.I, Uint32Array), 'SCALAR', U32, IDX) };
  });
  // materials
  J.samplers.push({ magFilter: 9729, minFilter: 9987, wrapS: 10497, wrapT: 10497 });
  X.mats.forEach((m) => {
    const mat = { name: m.name, pbrMetallicRoughness: { baseColorFactor: [...m.albedo, 1], metallicFactor: m.metal, roughnessFactor: m.rough }, doubleSided: m.side !== 0, extras: { type: m.type, vertexColors: m.vertexColors } };
    const e = m.emissive.map((v) => v * m.emissiveI), emax = Math.max(...e);
    if (emax > 0) { if (emax > 1) { mat.emissiveFactor = e.map((v) => v / emax); mat.extensions = { KHR_materials_emissive_strength: { emissiveStrength: emax } }; G.ext('KHR_materials_emissive_strength'); } else mat.emissiveFactor = e; }
    if (m.alphaPng) {
      const bv = G.view(Buffer.from(m.alphaPng, 'base64')); J.images.push({ bufferView: bv, mimeType: 'image/png', name: m.name + '_alpha' }); J.textures.push({ source: J.images.length - 1, sampler: 0 });
      mat.pbrMetallicRoughness.baseColorTexture = { index: J.textures.length - 1 }; mat.alphaMode = 'MASK'; mat.alphaCutoff = m.alphaTest || 0.5;
      mat.extras.albedoIsMean = true;   // baseColorFactor already holds the texture mean; the texture is there for its alpha
    }
    J.materials.push(mat);
  });
  const meshFor = new Map();
  const mesh = (gi, mi, name) => { const k = gi + ':' + mi; if (!meshFor.has(k)) { J.meshes.push({ name, primitives: [Object.assign({ material: mi, mode: 4 }, JSON.parse(JSON.stringify(geoAcc[gi])))] }); meshFor.set(k, J.meshes.length - 1); } return meshFor.get(k); };
  const instExt = (arr) => {
    const n = arr.length / 16, T = new Float32Array(n * 3), R = new Float32Array(n * 4), S = new Float32Array(n * 3);
    for (let i = 0; i < n; i++) { const d = decompose(arr, i * 16); T.set(d.t, i * 3); R.set(d.r, i * 4); S.set(d.s, i * 3); }
    G.ext('EXT_mesh_gpu_instancing');
    return { EXT_mesh_gpu_instancing: { attributes: { TRANSLATION: G.acc(T, 'VEC3', F), ROTATION: G.acc(R, 'VEC4', F), SCALE: G.acc(S, 'VEC3', F) } } };
  };
  const addNode = (n) => { J.nodes.push(n); J.scenes[0].nodes.push(J.nodes.length - 1); return J.nodes.length - 1; };
  for (const o of X.objects) {
    const n = { name: o.id, mesh: mesh(o.geo, o.mat, o.name || o.path), extras: { id: o.id, path: o.path, cat: o.cat, bake: o.bake, cast: o.cast } };
    if (o.instances) { n.extensions = instExt(fromB64(o.instances, Float32Array)); n.extras.count = o.count; } else n.matrix = o.matrix;
    addNode(n);
  }
  for (const t of X.trees) addNode({ name: t.id, mesh: mesh(t.geo, t.mat, t.group), extensions: instExt(fromB64(t.instances, Float32Array)), extras: { id: t.id, cat: 'tree', bake: 'tree', species: t.species, leaves: t.leaves, count: t.count } });
  // terrain grid
  {
    const T = X.terrain, VN = T.res + 1, H = fromB64(T.H, Float32Array), A = new Uint8Array(Buffer.from(T.albedo, 'base64'));
    const P = new Float32Array(VN * VN * 3), N = new Float32Array(VN * VN * 3), Cc = new Float32Array(VN * VN * 3), I = new Uint32Array(T.res * T.res * 6);
    for (let iz = 0; iz < VN; iz++) for (let ix = 0; ix < VN; ix++) {
      const i = iz * VN + ix; P[i * 3] = T.origin[0] + ix * T.cell; P[i * 3 + 1] = H[i]; P[i * 3 + 2] = T.origin[1] + iz * T.cell;
      const hx = H[iz * VN + Math.min(ix + 1, T.res)] - H[iz * VN + Math.max(ix - 1, 0)], hz = H[Math.min(iz + 1, T.res) * VN + ix] - H[Math.max(iz - 1, 0) * VN + ix], l = Math.hypot(hx, 2 * T.cell, hz);
      N[i * 3] = -hx / l; N[i * 3 + 1] = 2 * T.cell / l; N[i * 3 + 2] = -hz / l;
      for (let k = 0; k < 3; k++) Cc[i * 3 + k] = Math.pow(A[i * 3 + k] / 255, 2.2);
    }
    let k = 0; for (let iz = 0; iz < T.res; iz++) for (let ix = 0; ix < T.res; ix++) { const a = iz * VN + ix, b = a + VN, c = b + 1, d = a + 1; I[k++] = a; I[k++] = b; I[k++] = d; I[k++] = b; I[k++] = c; I[k++] = d; }
    J.materials.push({ name: 'terrain_snow', pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0, roughnessFactor: 1 }, extras: { vertexColors: true } });
    J.meshes.push({ name: 'terrain', primitives: [{ attributes: { POSITION: G.acc(P, 'VEC3', F, ARR, true), NORMAL: G.acc(N, 'VEC3', F, ARR), COLOR_0: G.acc(Cc, 'VEC3', F, ARR) }, indices: G.acc(I, 'SCALAR', U32, IDX), material: J.materials.length - 1 }] });
    addNode({ name: 'terrain', mesh: J.meshes.length - 1, extras: { id: 'terrain', cat: 'terrain', bake: 'terrain', res: T.res, cell: T.cell, origin: T.origin, W: T.W } });
  }
  // lights
  G.ext('KHR_lights_punctual');
  const L = [], E = X.env;
  const dirNode = (name, d, li) => { // glTF directional lights shine along −Z of the node: rotate −Z onto −d
    const [x, y, z] = d;
    // quaternion rotating (0,0,-1) to (-x,-y,-z)
    const v0 = [0, 0, -1], v1 = [-x, -y, -z], c = v0[0] * v1[0] + v0[1] * v1[1] + v0[2] * v1[2];
    const cr = [v0[1] * v1[2] - v0[2] * v1[1], v0[2] * v1[0] - v0[0] * v1[2], v0[0] * v1[1] - v0[1] * v1[0]], w = 1 + c, l = Math.hypot(cr[0], cr[1], cr[2], w);
    return addNode({ name, rotation: [cr[0] / l, cr[1] / l, cr[2] / l, w / l], translation: [d[0] * 500, d[1] * 500, d[2] * 500], extensions: { KHR_lights_punctual: { light: li } }, extras: { id: name, dir: d } });
  };
  L.push({ type: 'directional', name: 'moon', color: E.moon.color, intensity: E.moon.intensity }); dirNode('moon', E.moon.dir, 0);
  L.push({ type: 'directional', name: 'aurora', color: E.aurora.color, intensity: E.aurora.intensity }); dirNode('aurora', E.aurora.dir, 1);
  for (const p of X.lights) {
    // three point lights are in candela; glTF point intensity is candela too
    L.push({ type: p.type === 'SpotLight' ? 'spot' : 'point', name: p.name || p.parent || 'light', color: p.color, intensity: p.intensity, range: p.distance || undefined });
    addNode({ name: 'light_' + (L.length - 1), translation: p.pos, extensions: { KHR_lights_punctual: { light: L.length - 1 } }, extras: { id: 'light_' + (L.length - 1), parent: p.parent } });
  }
  J.extensions = { KHR_lights_punctual: { lights: L } };
  J.scenes[0].extras = { env: X.env, meta: X.meta };
  return G;
}

/* ------------------------------------------------------------------ main */
const H = await openWorld({ label: 'bake export', warm: Number(opt('warm', 22000)), headful: !!opt('headful'), quality: 'high' });
try {
  // settle at the crash site (rocks re-seated, packs loaded), then park the camera high so nothing is mid-stream
  await H.page.addScriptTag({ content: fs.readFileSync(path.join(GAME, 'tools', 'bake', 'page-export.js'), 'utf8') });
  const t0 = Date.now();
  const X = await H.page.evaluate((o) => window.BAKE_EXPORT(o), { terrainRes: Number(opt('terrain-res', 1024)) });
  H.log(`page export ${Date.now() - t0} ms · ${X.objects.length} objects · ${X.trees.length} tree parts · ${X.geos.length} geometries · ${X.mats.length} materials · ${X.lights.length} point lights`);
  H.log('skipped', JSON.stringify(X.skipped));
  if (H.errors.length) H.log('page errors', H.errors.slice(0, 5));
  for (const o of X.objects) o.bake = bakeMode(o);
  const G = buildGlb(X);
  G.write(path.join(OUT, 'scene.glb'));
  // manifest (no geometry)
  const man = {
    version: 1, date: X.meta.date, source: 'open-world.html (' + X.meta.quality + ')', glb: 'scene.glb', coords: 'three.js world (Y up, metres)', env: X.env, meta: X.meta,
    terrain: { res: X.terrain.res, cell: X.terrain.cell, origin: X.terrain.origin, W: X.terrain.W, source: X.terrain.source },
    geos: X.geos.map((g) => ({ key: g.key, name: g.name, verts: g.n, tris: g.tris, uv: !!g.UV, color: !!g.COL })),
    mats: X.mats.map(({ alphaPng, ...m }) => Object.assign(m, { alphaMask: !!alphaPng })),
    objects: X.objects.map(({ instances, matrix, ...o }) => Object.assign(o, { pos: matrix ? [matrix[12], matrix[13], matrix[14]] : null })),
    trees: X.trees.map(({ instances, ...t }) => t),
    lights: X.lights, skipped: X.skipped,
  };
  fs.writeFileSync(path.join(OUT, 'export.json'), JSON.stringify(man, null, 1));
  const cats = {}; for (const o of man.objects) { const k = o.cat + '/' + o.bake; cats[k] = (cats[k] || 0) + (o.count || 1); }
  H.log('categories', JSON.stringify(cats));
  H.log('wrote', path.join(OUT, 'scene.glb'), (fs.statSync(path.join(OUT, 'scene.glb')).size / 1e6).toFixed(1) + ' MB');
} finally { await H.close(); }
