#!/usr/bin/env node
/* tools/interact/author.mjs — author the interaction passport (modules/interact-data.js) from the drawn geometry.
 *
 *   node tools/interact/author.mjs [--kinds <regex on 'name|vn'>] [--out modules/interact-data.js] [--merge] [--no-shots]
 *
 * One browser (benchmark lock). For every interactable kind: pick a mid-size reference instance, scan its drawn
 * triangles (tools/interact/author-page.js → AUTH.author), store the proposed points in the kind's frame, and save a
 * contact sheet (2 views, markers: cyan = wall patch that takes two palms, blue = one palm / shoulder, orange = top rim)
 * to stand/interact-author/<kind>.jpg — look at them before trusting a kind. --merge keeps kinds not re-authored.
 */
import fs from 'node:fs';
import path from 'node:path';
import { openGame, ROOT, OUT, sleep } from '../qa/harness.mjs';
const argv = process.argv.slice(2);
const opt = (k, d) => { const i = argv.indexOf('--' + k); return i >= 0 ? argv[i + 1] : d; };
const outFile = path.resolve(ROOT, opt('out', 'modules/interact-data.js'));
const shotDir = path.join(OUT, 'interact-author'); fs.mkdirSync(shotDir, { recursive: true });
// every interactable kind in the brief (+ a few structures of the same families); trunks by name
const KINDS = opt('kinds', '^(boulder|rock|rock_flat|rock_outcrop|st_ruin_wall|st_ruin_column|st_ruin_arch|kestrel|kestrel_wing|kestrel_tail|station_dome|station_module|struct_hab_module|struct_radome|vehicle_rover_sev|tool_crate|crate_stack|st_tent_dome|st_tent_tunnel|st_tent_polar|st_tent_polar_stove|st_drum_depot|station_sledge|prop_crate_wood|st_sledge|st_snowcat|st_cairn|st_inuksuk|st_rowboat|spireN|spireE|spireW|firepit|st_pole_fallen|crate_wood|crate_wood_02|drum_blue|barrel_steel|prop_barrel_01|prop_crate_military|prop_generator|prop_propane_tank|lamp_post|st_pole|st_pole_tr|tree_[a-z_]+)\\|');
const H = await openGame({ label: 'interact author', quality: 'high', size: [960, 640] });
const data = { version: 1, generated: new Date().toISOString(), tool: 'tools/interact/author.mjs', kinds: {}, alias: {} };
if (argv.includes('--merge') && fs.existsSync(outFile)) { try { const src = fs.readFileSync(outFile, 'utf8'); const j0 = src.indexOf('window.INTERACT_DATA = '), j = JSON.parse(src.slice(src.indexOf('{', j0), src.lastIndexOf('}') + 1)); Object.assign(data.kinds, j.kinds || {}); Object.assign(data.alias, j.alias || {}); } catch (e) { console.log('merge: could not read', outFile, e.message); } }
const report = [];
try {
  await H.newGame();
  for (const f of ['tools/interact/page.js', 'tools/interact/author-page.js']) await H.page.evaluate(fs.readFileSync(path.join(ROOT, f), 'utf8'));
  await H.page.evaluate(() => { const hud = document.querySelectorAll('#hud, .hud, #prompt, #cmp, #mini'); hud.forEach((e) => { e.style.visibility = 'hidden'; }); });
  const keys = await H.page.evaluate((re) => [...AUTH.kinds(re).keys()].sort(), KINDS);
  console.log('kinds', keys.length, keys.join(' '));
  for (const key of keys) {
    const r = await H.page.evaluate(async (k) => { try { return await AUTH.author(k); } catch (e) { return { key: k, error: String(e.stack || e).slice(0, 400) }; } }, key);
    if (r.error || !r.rec) { console.log('  ✗', key, r.error); report.push({ key, error: r.error }); continue; }
    if (!r.trunk && !r.rec.pts.length) { console.log('  ·', key, 'no points (nothing reachable-shaped)'); report.push({ key, pts: 0 }); continue; }
    data.kinds[key] = r.rec; write();
    report.push({ key, pts: r.rec.pts ? r.rec.pts.length : 0, walls: r.walls, tops: r.tops, trunk: !!r.trunk, rAt: r.rec.rAt });
    console.log('  ✓', key.padEnd(34), r.trunk ? 'trunk rAt ' + JSON.stringify(r.rec.rAt) : `walls ${r.walls} tops ${r.tops}`);
    if (r.trunk || argv.includes('--no-shots')) continue;
    await H.page.evaluate(() => AUTH.markers(true));
    for (const v of [0, 1]) {
      await H.page.evaluate((k) => AUTH.view(k), v); await sleep(700);
      await H.page.screenshot({ path: path.join(shotDir, key.replace(/[|]/g, '_') + '-v' + v + '.jpg'), type: 'jpeg', quality: 70 });
    }
    await H.page.evaluate(() => { AUTH.markers(false); DBG.camOv = null; });
  }
  // same model under another name (echo stones are ruin pieces): reuse the kind with the same vertex count + frame
  const all = await H.page.evaluate(() => [...AUTH.kinds('').keys()]);
  for (const k of all) {
    if (data.kinds[k] || !/^echo\d/.test(k)) continue;
    const vn = k.split('|')[1], to = Object.keys(data.kinds).find((q) => q.split('|')[1] === vn && data.kinds[q].frame === 'anchors');
    if (to) data.alias[k] = to;
  }
} finally { await H.close(); }
write();
fs.writeFileSync(path.join(shotDir, 'report.json'), JSON.stringify(report, null, 1));
function write() {
const body = JSON.stringify(data);
fs.writeFileSync(outFile, `/* modules/interact-data.js — interaction passport points per kind. GENERATED by tools/interact/author.mjs (${data.generated}); see INTERACT.md.
 * kinds['name|vertexCount'] = { frame: 'anchors'|'obj'|'trunk', pts: [[x,y,z, nx,ny,nz, ex,ez, type(1 wall|2 top), y0,y1, width]], anchors?: [[vertexIndex, x,y,z]], ... } */
window.INTERACT_DATA = ${body};
`);
console.log('wrote', path.relative(ROOT, outFile), (body.length / 1024).toFixed(1) + ' KB,', Object.keys(data.kinds).length, 'kinds,', Object.keys(data.alias).length, 'aliases');
}
