'use strict';
// All texts in English. Keys match text.ru.js.
L.def('content/text.en', () => {
  const U = L.use('core');
  U.TXT = U.TXT || {};
  U.TXT.en = {
    ui: {
      appName: 'Uptime', tagline: 'You build a service. It breaks. You fix it.', start: 'Start', play: 'Play', firstNote: '3 minutes, we’ll show you',
      levels: 'Levels', more: 'More', daily: 'Daily task', dailyNote: 'same for everyone', survival: 'Survival', survivalNote: 'how long can you last',
      sandbox: 'Sandbox', sandboxNote: 'no rules', learn: 'Guide', learnNote: 'what’s what', level: 'Level', tutorial: 'Tutorial',
      answerToStart: 'Answer to begin', go: 'Start', soon: 'At {at}s: {name}', newBlock: 'New',
      goalAvail: '{v}% of people get a reply', goalP95: 'faster than {v} ms', goalBudget: 'under {v}/mo', goalQueue: 'queue younger than {v} s', goalLag: 'lag ≤ {v} s',
      goalInv: 'no integrity violations', goalHang: 'no stuck reservations', goalSec: 'all security checks', goalMissed: 'everyone gets every event', goalLost: 'no lost writes',
      answered: 'Answered', wait: 'Wait', moneyMo: 'Money/mo', rps: 'Requests/s', cash: 'Money', day: 'Day', today: 'Today', limit: 'Limit',
      termAvail: 'availability', termP95: 'p95: 95 of 100 are faster', termCost: 'cost', termRps: 'rps',
      launch: 'Launch', pause: 'Pause', paused: 'Paused · you can edit', linkHint: 'Connect: drag from ○ to a block',
      hint: 'Hint', hintQ: 'Question', hintDir: 'Direction', hintSol: 'Solution', pauseToEdit: 'Pause to edit',
      remove: 'Remove', removeLink: 'Delete link', link: 'Link', perMonth: '/mo', loadTest: 'Load test', loadTestDone: 'Limit ≈ {v}',
      win: 'It held!', lose: 'It broke', next: 'Next', again: 'Retry', fix: 'Fix', toLevels: 'Levels', menu: 'Menu', details: 'Details',
      gotAnswer: 'got a reply', waited: 'wait', inMonth: 'per month', predictOk: 'Prediction right', predictMiss: 'Prediction missed: {v}',
      thought: 'Engineer’s thought', inLife: 'In real life', decision: 'Decision', pros: 'Pros', cons: 'Cons', whereThin: 'Where it was close', whatBroke: 'What broke',
      path: 'Request path', pathNote: 'what the wait was made of', typical: 'Typical request', slowest: 'Slowest ({v})',
      tutWin: 'Reliable, fast, cheap', tutWinNote: 'You found the bottleneck and fixed it. That’s an engineer’s job.',
      starGoals: 'Goals', starObj: 'Bonus goal', starCheap: '≤ 80% of money', ach: 'Achievements', achGot: 'Achievement: {v}',
      survTitle: 'Keep the company afloat', survGrow: 'Traffic grows', survGrowNote: 'every day', survRev: 'Revenue', survRevNote: 'per reply',
      survInc: 'Incidents', survIncNote: 'more and more', survEnd: 'Game over', survEndNote: 'money < 0 or 3 bad days', diffEasy: 'Calm', diffNorm: 'Normal', diffHard: 'Hard', growthPerDay: 'growth {v}%/day',
      survDayBad: 'Day {d}: {v} — users are leaving', survNoMoney: 'Out of money', survLeft: 'Three bad days in a row — users left', survQuit: 'You stopped the run',
      days: 'days', record: 'record', peak: 'peak traffic', left: 'left', best: 'best result', moneyByDay: 'Money by day', hitHardest: 'What hit hardest',
      noTarget: 'Node has nowhere to send requests', firstRun: 'Launch first', ramping: 'Ramping up traffic until it breaks', saved: 'Saved to slot {v}',
      learnComp: 'Components', learnConc: 'Concepts', learnHow: 'How to play', engCycle: 'Engineering is a cycle',
      lang: 'Русский', notice: 'noticed after 20 s', warnCert: 'Certificate expires in 25 s',
      rollback: 'Roll back version', renew: 'Renew certificate', renewed: 'Certificate renewed', rolledBack: 'Rolling back {v}',
      group: 'Group', groupSvc: 'Service', groupAgg: 'Aggregate', groupCtx: 'Context', instances: 'Instances', bulkhead: 'Inner bulkheads', size: 'size {v} — by module count',
      kind: 'How they talk', need: 'What’s needed', acl: 'Anti-corruption layer (ACL)',
      fog: 'Can’t see — need {v}', fogMetrics: 'monitoring', fogLogs: 'logs', fogTraces: 'tracing',
      error: 'Error', loadTestNote: 'Ramping traffic on a copy until it breaks', loadTestBtn: 'Test',
      sbTraffic: 'Traffic', sbPresetRead: 'Reads', sbPresetFiles: 'Files', sbPresetWrite: 'Writes', sbPresetPersonal: 'Personal', sbPresetFar: 'Far away',
      sbLimit: 'Limit', bad: 'bad', good: 'good', tiers: 'Groups',
      connections: 'Connections', pods: 'Pods', pending: 'waiting for room', waiting: 'waiting', inQueue: 'In queue', load: 'Load', hits: 'Hits', fromEdge: 'From edge',
      works: 'Working', booting: 'booting', notKeeping: 'Falling behind', status: 'Status', down: 'down', lagLabel: 'Lag', latency: 'Latency', errors: 'Errors from here',
    },
    tiers: {
      basics: ['Basics', 'servers, load balancing, cache, database'],
      load: ['Load and reliability', 'spikes, queues, brokers, failures'],
      observe: ['Observability and quality', 'metrics, logs, traces, tests'],
      platform: ['Platform', '12-factor, Kubernetes, sockets, security, regions'],
      arch: ['Architecture', 'monolith, microservices, DDD, events, processes'],
    },
    groups: { net: 'Entry', route: 'Routing', comp: 'Compute', async: 'Background', data: 'Data', x: 'External', obs: 'Observe and protect' },
    comp: {
      users: ['Users', 'All requests come from here', 'Guests at the door'],
      dns: ['DNS', 'Sends people to the right region', 'Signpost at a fork', 'Long TTL — slow switchover too.'],
      cdn: ['CDN', 'Answers close to the user', 'Pickup points near home', 'Anything not cached still comes to you.'],
      waf: ['Firewall', 'Blocks bots at the door', 'Bouncer at the door', 'Too strict — blocks your own.'],
      lb: ['Load balancer', 'Spreads requests across servers', 'Host at the door', 'Without checks it sends requests to the dead.'],
      ingress: ['Ingress', 'Entry into the Kubernetes cluster', 'Factory gatehouse', 'The certificate is its job too.'],
      compute: ['Servers', 'Your code on machines', 'Cashiers', 'New machines open new database connections.'],
      deploy: ['Deployment', 'Pods with your code in Kubernetes', 'Work shift', 'Without a readiness probe, traffic hits pods not ready yet.'],
      mod: ['Module', 'Part of the app: orders, payments, stock…', 'Company department', 'Where it lives and how it talks — your call.'],
      wsgw: ['Sockets', 'Hold persistent connections', 'Open phone lines', 'After a restart everyone reconnects at once.'],
      nodes: ['Cluster nodes', 'Machines where pods live', 'Building for the shifts', 'Pods without room have to wait.'],
      cache: ['Cache', 'Memory in front of the database', 'Display case of ready food', 'If reads are personal — barely any hits.'],
      db: ['Database', 'Stores data, takes writes', 'Stockroom', 'Replicas don’t help writes.'],
      storage: ['Storage', 'Files and images', 'Self-serve fridge', 'Files through servers — expensive.'],
      queue: ['Queue', '“Later” tasks: one task — one worker', 'Order rail', 'Without workers it only piles up.'],
      broker: ['Broker', 'Event log: each group reads everything', 'Radio: everyone on one station', 'Parallelism ≤ number of partitions.'],
      worker: ['Workers', 'Drain the queue or read events', 'Kitchen helpers', 'Too few workers — work piles up.'],
      ext: ['External system', 'Someone else’s service: payments, partner, ERP', 'Supplier', 'You can’t speed it up — only protect yourself.'],
      vpn: ['VPN', 'Secure tunnel to a private system', 'Service corridor', 'One tunnel — one point of failure.'],
      saga: ['Saga', 'Runs a process, undoes steps on failure', 'Order dispatcher', 'Without compensations a failure leaves loose ends.'],
      monitor: ['Monitoring', 'Metrics: see load and incidents', 'Cameras and a dispatcher', 'Speeds up nothing, but without it you’re blind.'],
      logs: ['Logs', 'See where and why errors happen', 'Shift logbook', 'Debug level is expensive.'],
      tracing: ['Tracing', 'See where time is lost', 'Order stopwatch', 'Recording every request — expensive.'],
      tests: ['Tests', 'Catch bugs before production', 'Tasting before serving', 'Even full tests don’t catch everything.'],
      vault: ['Secrets', 'Vault for passwords and keys', 'Safe', 'A password in code has already leaked.'],
    },
    ctl: {
      failover: 'Fail over by health', ttl: 'Keep response', api: 'Cache API responses', sens: 'Bot protection', rl: 'Per-client limit',
      checks: 'Health checks', tls: 'Certificate', kind: 'Type', size: 'Size', n: 'Machines', auto: 'Autoscale', min: 'Minimum', max: 'Maximum', tgt: 'Target load',
      pool: 'DB connections', timeout: 'Timeout', retries: 'Retries', backoff: 'Pause between retries', breaker: 'Circuit breaker', state: 'Sessions', conf: 'Config', logsTo: 'Logs',
      rollout: 'Rollout', zone: 'Zone', region: 'Region', cloud: 'Cloud', cpu: 'CPU per pod', hpa: 'Pod autoscaling (HPA)', ready: 'Readiness probe',
      strategy: 'Update', limit: 'CPU limits', spread: 'Spread across nodes', pdb: 'PodDisruptionBudget', mem: 'Memory, GB', replica: 'Cache replica', rep: 'Read replicas',
      mz: 'Two zones (×2 price)', pub: 'Reachable from internet', xr: 'Copy in another region', parts: 'Partitions', tunnels: 'Tunnels', drain: 'Graceful drain on update',
      level: 'Level', sample: 'Record requests', suite: 'Suite', count: 'Nodes', ca: 'Cluster autoscaler', grp: 'Group', ttlDns: 'TTL',
      workersN: 'Workers', autoWorkers: 'By queue depth', wsN: 'Instances', cpuNode: 'Node',
    },
    opt: {
      ttl: { short: 'short', long: 'long', s: '10 s', m: '5 min', h: '1 h' }, sens: { off: 'off', low: 'low', mid: 'medium', high: 'strict' }, rl: { off: 'none', loose: 'loose', strict: 'strict' },
      tls: { none: 'none', manual: 'manual', auto: 'auto' }, kind: { vm: 'VM · 25 s', ctr: 'Container · 6 s' }, timeout: { 1: '1 s', 3: '3 s', 10: '10 s' },
      state: { local: 'in memory', shared: 'in cache' }, conf: { baked: 'in image', env: 'in env' }, logsTo: { file: 'to file', stdout: 'to stream' },
      rollout: { all: 'all at once', canary: 'canary' }, strategy: { recreate: 'recreate', rolling: 'rolling' }, xr: { none: 'none', async: 'async', sync: 'sync' },
      level: { debug: 'debug', info: 'info', error: 'error' }, sample: { 1: '1%', 10: '10%', 100: '100%' }, suite: { none: 'none', unit: 'unit', int: '+integration', full: '+e2e' },
      cloud: { C1: 'Cloud 1', C2: 'Cloud 2' }, region: { R1: 'Region 1', R2: 'Region 2' },
    },
    edgeKind: { sync: 'Sync', cmd: 'Command', evt: 'Event', db: 'Shared DB' },
    need: { reply: 'needs a reply now', must: 'must get done', fyi: 'FYI', inv: 'atomic, together' },
    inc: {
      spike: 'Surge ×{mul}', crash: 'Machine down', hang: 'Server hung', zone: 'Zone {zone} went dark', region: 'Region {region} down', cloud: 'Cloud {cloud} is down',
      cacheLoss: 'Cache lost', bots: 'Bots', price: 'Prices +{pct}%', extSlow: 'External service is slow', vpnDown: 'VPN tunnel down', certExpire: 'Certificate expired',
      badDeploy: 'Bad release', rollout: 'New version rollout', nodeFail: 'Cluster node down', drain: 'Node upgrade', noisy: 'Noisy neighbor',
      wsRestart: 'Sockets restart', cfgChange: 'DB password changed', diskFull: 'Disk full', leak: 'Password leaked', scan: 'Database scan',
      groupDown: 'Service down', contract: 'API changed', migration: 'Schema migration', addConsumer: 'New subscriber', heavy: 'Heavy report',
    },
    cause: {
      noEntry: ['Users have nowhere to go', 'Connect Users to the first block.'], noTarget: ['Node has nowhere to send requests', 'Make sure every node leads somewhere.'],
      noDb: ['Servers can’t see the database', 'Connect Servers to the Database.'], dead: ['The only machine went down', 'At least two behind a load balancer.'],
      computeSat: ['Servers are swamped', 'More machines or autoscaling.'], scaleLag: ['Capacity didn’t keep up', 'Headroom in advance or fast startup.'],
      threads: ['Threads stuck waiting', 'Short timeout, circuit breaker or a queue.'], timeout: ['Gave up waiting for a reply', 'Timeouts and async.'],
      dbSat: ['Database overloaded', 'Cache, replicas or a bigger database.'], dbConn: ['Out of DB connections', 'Smaller pool or fewer machines.'],
      dbZone: ['Database was in the dark spot', 'Copy in another zone or region.'], dbFailover: ['Database was failing over', 'A sync copy fails over faster.'],
      zone: ['All capacity was in one place', 'Spread across zones and keep headroom.'], hung: ['Server hung', 'Health checks on the load balancer.'],
      noChecks: ['Load balancer sent traffic to the dead', 'Turn on health checks.'], detect: ['Seconds until detection', 'The living need headroom.'],
      fp: ['Firewall blocks your own', 'Lower sensitivity or loosen the limit.'], bug: ['New version errors', 'Tests, canary, rollback.'],
      notReady: ['Traffic to pods not ready', 'Turn on the readiness probe.'], session: ['Users lose sessions', 'Keep sessions in external storage.'],
      rebuild: ['Rebuild due to config', 'Config in env, not in the image.'], disk: ['Logs filled the disk', 'Log to a stream.'],
      breach: ['Breach', 'Secrets in a vault, database closed.'], cert: ['Certificate expired', 'Automatic renewal.'],
      extSat: ['External service can’t keep up', 'Cache in front of it, fewer retries.'], vpn: ['Tunnel down', 'A second tunnel.'], dns: ['People went to a dead region', 'DNS with checks and short TTL.'],
      wsSat: ['Sockets overloaded', 'More instances, pause on reconnect.'], disconnected: ['People disconnected', 'More instances, graceful drain.'],
      backplane: ['Messages didn’t reach neighbors', 'Shared bus between instances.'], crash: ['A service fell — and so did everyone waiting on it', 'Don’t wait for what isn’t needed now.'],
      redeploy: ['Had to redeploy together', 'Don’t share tables between services.'], contract: ['Someone else’s API broke calls', 'Anti-corruption layer (ACL) at the seam.'],
      needReply: ['A reply was needed now, but the request went to a queue', 'This needs a sync call.'], breaker: ['Circuit breaker cut off a dependency', 'That’s fine — it keeps the rest alive.'],
      loop: ['Request went in circles', 'Break the loop.'],
    },
    slow: { dist: ['Distance to the user', 'Closer to people: CDN or region.'], cq: ['Queue at servers', 'More machines.'], dq: ['Queue in the database', 'Offload the database.'],
      conn: ['Waiting for a DB connection', 'Smaller pool.'], side: ['Write waits for background work', 'Queue and workers.'], over: ['Overload', 'Capacity for the peak.'],
      hop: ['Many network hops', 'Fewer sync calls between services.'], ext: ['Waiting on external service', 'Cache or async.'] },
    parts: { base: 'Work and network', dist: 'Distance', cq: 'Queue at servers', dq: 'Queue in database', conn: 'DB window', side: 'Background work', over: 'Overload', hop: 'Network hops', ext: 'External service' },
    pm: { hit: ['Cache barely hits', 'Reads are personal — you need replicas.', 'More memory or longer TTL.'], static: ['Files go through servers', 'Storage behind the load balancer or CDN.'],
      bots: ['Bots eat capacity', 'Firewall with bot protection.'], queue: ['Work can’t keep up', 'More workers or partitions.'], cost: ['Over budget', 'Machines sit idle — remove extras.', 'Remove work, not just machines.'],
      blind: ['Incident noticed after 20 s', 'Monitoring cuts it to 2 s.'], inv: ['Data integrity broken', 'Invariant — inside one aggregate, synchronously.'],
      hanging: ['Unpaid reservations stuck', 'Saga with compensation.'], missed: ['Not everyone got the events', 'Broker instead of a queue.'], lost: ['Last writes lost', 'Sync copy — no loss.'],
      lag: ['Background work fell behind', 'More capacity at the receiver.'], sec: ['Holes left open', 'Secrets, closed database, firewall, TLS.'],
      good1: 'No node overheated', good2: 'Cache served {v} reads', good3: 'The incident went almost unnoticed', good4: 'Bots stopped at the door', good5: 'Under 80% of budget' },
    obj: {
      maxUtil: 'No node above {v}%', incAvail: 'During incident — at least {v}%', cacheHit: 'Cache catches {v}% of reads', queueAge: 'Queue younger than {v} s', conn: 'Connections within DB limit',
      bots: 'Block {v}% of bots', noReplica: 'No read replicas', monitor: 'Monitoring on the board', noIdle: 'No idle workers', lag: 'Lag ≤ {v} s',
      maxGroups: 'At most {v} groups', noShared: 'No shared tables', egress: 'Cross-cloud ≤ {v} rps', lost: 'Not a single lost write', flag: 'Run a load test',
      has: { monitor: 'Monitoring on the board', tracing: 'Tracing on the board', tests: 'Tests in the pipeline', saga: 'A saga runs the process', mod: 'Subscriber added without touching orders' },
      cfg: { logs: 'Logs at info level', deploy_ready: 'Readiness probe on', nodes: 'Cluster autoscaler', deploy_pdb: 'PodDisruptionBudget', deploy_limit: 'Limits on all', wsgw: 'Graceful drain', lb: 'Certificate renews itself', vpn: 'Two tunnels', compute: 'Server autoscaling' },
    },
    concepts: [
      ['Wait (p95)', '95 of 100 requests are faster than this. We watch the unlucky, not the average.'],
      ['Availability', 'Share of requests that got a reply.'],
      ['Server queue', 'Waiting starts long before 100% load.'],
      ['Out, not up', 'Four small servers wait less than one big one.'],
      ['Headroom', 'Capacity is bought before the incident.'],
      ['Cache', 'Only works on repeats.'],
      ['Queue and broker', 'Queue: each task to one. Broker: everything to each group, parallelism ≤ partitions.'],
      ['Timeouts and retries', 'A slow dependency holds threads. Retries without a pause finish it off.'],
      ['Observability', 'Metrics — where it’s hot. Logs — what broke. Traces — where time goes.'],
      ['12-factor', 'No state in the process, config in env, logs as a stream, fast startup.'],
      ['Kubernetes', 'Pods, readiness, HPA, nodes, PDB, limits.'],
      ['Regions and clouds', 'DNS switches, data is copied, cross-cloud traffic costs money.'],
      ['Monolith and microservices', 'A service boundary goes where little talk crosses it.'],
      ['DDD', 'Contexts follow language and links. An aggregate is an integrity boundary.'],
      ['Commands and events', 'Command: “do it” to one. Event: “it happened” to all who care.'],
      ['Saga', 'A long process of steps with compensations.'],
    ],
    engCycle: [['Understand load', 'who, how much, what they ask'], ['Design', 'blocks and links'], ['Test', 'under load'], ['Notice', 'what went wrong'], ['Find the cause', 'the bottleneck'], ['Fix', 'and test again'], ['Write it down', 'so it won’t repeat']],
    ach: { first: ['First launch', 'Beat the first level'], hit90: ['Memory wins', 'Cache catches 90% of reads'], three: ['Clean', '3★ on any level'], allch: ['Graduate', 'Beat all levels'],
      surv7: ['A week', '7 days in Survival'], surv30: ['A month', '30 days in Survival'], daily: ['Every day', 'Beat the daily task'], million: ['Million', '1,000,000 rps in the sandbox'], waste: ['Big spender', '$10,000/mo on <500 rps'],
      tier5: ['Architect', 'Beat the “Architecture” group'] },
    daily: { shop: 'Shop of the day', chat: 'Messenger of the day', news: 'News of the day', social: 'Social network of the day', video: 'Video of the day', story: '{v} rps and two incidents.', teach: 'One seed for everyone' },
    coach: [
      'These are people. They ask your app for something.', 'They need someone to answer — a server.', 'Connect people to the server so requests know where to go.', 'All set. Launch!',
      'Dots are requests. The bar shows how busy the server is.', 'Four times more people. The server can’t keep up — it’s red.', 'You need more servers. Add two more.', 'Done. Let’s go on.',
      'Three numbers on top: answered, waited, cost. All three should be green.',
    ],
    coachBtn: ['Next', 'Place a server', 'Connect', 'Launch', 'Got it', 'Look at the server', 'Add two', 'Continue', 'Got it'],
    levels: {
      intro: { title: 'How a service works', story: 'People open the app — someone has to answer them.', teach: 'Bottleneck and balance' },
      hello: { title: 'Hello, internet', story: 'First server, first 120 requests per second.', teach: 'A server answers requests',
        predict: ['How many servers for 120 requests per second?', ['One', 'Five', 'Ten'], 0, 'One small one handles about 300 per second. Extras are just money.'],
        lesson: 'Count the load first, then pick the size.', real: 'Every site starts with one server.',
        hints: ['Who will answer users?', 'You need one “Servers” block.', 'Servers ×1 and a link from Users.'],
        adr: ['One small server', ['cheap', 'simple'], ['it falls — the site is down']] },
      two: { title: 'One isn’t enough', story: 'Traffic grows, and machines sometimes fail.', teach: 'Several machines behind a load balancer',
        predict: ['Traffic grows, one machine will fail. What happens to one big server?', ['It holds — it’s powerful', 'Everything is down while it restarts', 'A bit slower'], 1, 'One server — one point of failure.'],
        lesson: 'One machine — one point of failure.', real: 'Servers fail every day. Services live on because there are several.',
        hints: ['What if the only machine fails?', 'A load balancer and several machines.', 'Users → Load balancer → Servers ×5.'],
        adr: ['Several small ones behind a balancer', ['one failing goes unnoticed', 'grows in steps'], ['a bit pricier than one']] },
      files: { title: 'Heavy files', story: 'Two thirds of requests are images.', teach: 'Files go to storage',
        predict: ['Where is it cheaper to keep images?', ['On the code servers', 'In separate storage', 'In the database'], 1, 'An image needs no computing.'],
        lesson: 'Don’t push through the expensive path what can be served cheaply.', real: 'Images and video almost always live in separate storage.',
        hints: ['Do you need a cook to grab a drink from the fridge?', 'Storage behind the load balancer.', 'Load balancer → Servers ×2 and → Storage.'],
        adr: ['Files from storage', ['fewer servers', 'cheaper'], ['one more service']] },
      far: { title: 'Across the ocean', story: 'All users are overseas.', teach: 'CDN cures distance',
        predict: ['Overseas users complain it’s slow. Will more servers help?', ['Yes, more is faster', 'No, it’s the distance', 'Need a stronger server'], 1, 'Servers don’t shorten the road.'],
        lesson: 'Distance is waiting too, and capacity can’t buy it off.', real: 'Big sites have edge points all over the world.',
        hints: ['Where is time spent: working or traveling?', 'CDN as the first block.', 'CDN (long + API cache) → Load balancer → Servers and Storage.'],
        adr: ['CDN with long cache', ['fast everywhere', 'offloads servers'], ['data may be slightly stale']] },
      readheavy: { title: 'Everyone reads the same', story: 'Short links: 90% reads, all the same ones.', teach: 'Cache for repeat reads',
        predict: ['Everyone asks for the same links. What offloads the database cheapest?', ['Bigger database', 'Cache', 'More servers'], 1, 'The same thing is cheaper to remember.'],
        lesson: 'The cheapest request is the one that never reaches the database.', real: 'News and product pages are almost always served from cache.',
        hints: ['Do requests repeat?', 'Cache between servers and database.', 'Servers → Cache (4 GB, 1 h) → Database S.'],
        adr: ['Read cache', ['small database', 'fast'], ['stale data']] },
      feed: { title: 'Personal feed', story: 'Everyone has their own feed — almost no repeats.', teach: 'Replicas when cache is powerless',
        predict: ['Almost no repeats. Will cache help?', ['Yes, always', 'Barely', 'If it’s huge'], 1, 'Cache only works on repeats.'],
        lesson: 'Pick the tool by the shape of the load.', real: 'Personal feeds are among the most expensive problems.',
        hints: ['Would cache help if everyone needs something different?', 'Read replicas on the database.', 'Database M with 2 replicas, no cache.'],
        adr: ['Read replicas', ['scale reads', 'don’t depend on repeats'], ['don’t speed up writes', 'replica lag']] },
      cachegone: { title: 'Cache lost', story: 'All is fine, then the cache vanishes for 40 seconds.', teach: 'Load without crutches',
        predict: ['The cache vanishes. What happens to the database?', ['Nothing', 'It gets all reads at once', 'It gets faster'], 1, 'The database was sized to work with a cache.'],
        lesson: 'Know how much the system takes without its crutches.', real: 'Cache restarts have taken down big services more than once.',
        hints: ['What happens to the database without cache?', 'Cache replica.', 'Turn on “Cache replica” on the cache.'],
        adr: ['Cache replica', ['cheap', 'database stays small'], ['double memory']] },
      launch: { title: 'Launch day', story: 'At 30 s, an announcement: traffic ×4 instantly.', teach: 'Headroom is bought before the incident',
        predict: ['Traffic quadruples instantly. Will autoscaling keep up?', ['It will', 'No: a machine boots in 25 s', 'Doesn’t matter'], 1, 'A new machine isn’t ready right away.'],
        lesson: 'Headroom is bought before the incident, not during it.', real: 'Ticket sites crash in the first minute of sales.',
        hints: ['How many machines at peak? How long does a new one boot?', 'Headroom in advance or containers.', 'Servers ×8 or autoscale with containers and minimum 5.'],
        adr: ['Peak headroom in advance', ['peak is no threat'], ['paying for idle']] },
      grow: { title: 'Word of mouth', story: 'Traffic grows 6× in two minutes.', teach: 'Autoscaling for smooth growth',
        predict: ['Growth is smooth. What’s cheaper?', ['Buy for the peak', 'Add as it grows', 'Nothing'], 1, 'Autoscaling catches smooth growth.'],
        lesson: 'Predictable growth — pay as you go.', real: 'Clouds bill by the minute exactly for this.',
        hints: ['Do you need peak headroom from second one?', 'Autoscaling.', 'Minimum 2, maximum 8, target 50%.'],
        adr: ['Autoscaling', ['pay for what’s needed'], ['too slow for a sudden jump']] },
      conns: { title: 'Connection ceiling', story: 'Servers grow, and the database chokes though it’s not busy.', teach: 'Database connections',
        predict: ['The database is slow though barely busy. Why?', ['Too small', 'Out of connections', 'Network'], 1, 'Each machine holds its own connections.'],
        lesson: 'The bottleneck isn’t always where it’s hot.', real: '“Added servers — got worse” is a classic.',
        hints: ['How many connections, and what’s the database limit?', 'Connection pool on servers.', 'DB connections: 10 instead of 20.'],
        adr: ['Small pool', ['database doesn’t choke'], ['less parallelism per machine']] },
      nowait: { title: 'Don’t make them wait', story: 'Each write drags emails and recalcs: +450 ms.', teach: 'Slow stuff goes to a queue',
        predict: ['How not to keep the person waiting?', ['Do everything faster', 'Accept now, rest later', 'Stronger servers'], 1, 'The person needs an “accepted” reply.'],
        lesson: 'Don’t make people wait for what isn’t needed now.', real: 'The “order received” email arrives a minute later — that’s a queue.',
        hints: ['Must they wait for the email?', 'Queue and workers.', 'Servers → Queue → Workers ×3.'],
        adr: ['Task queue', ['fast reply', 'smooths peaks'], ['work is done later']] },
      broker: { title: 'Everyone needs events', story: 'Order placed — emails, analytics and stock all need it.', teach: 'Queue vs broker',
        predict: ['Three systems read one queue. Will each get all orders?', ['Yes', 'No: each order goes to one of them', 'Only the first'], 1, 'A queue hands a message to one.'],
        lesson: 'Queue — split the work. Broker — hand an event to all.', real: 'Kafka and the like — a log many read.',
        hints: ['Who gets the order if three share one queue?', 'Broker, each system has its own group.', 'Broker with 5 partitions, 5 workers each.'],
        adr: ['Broker with partitions', ['everyone gets everything', 'can re-read'], ['parallelism ≤ partitions']] },
      retry: { title: 'Payments are slow', story: 'The payment provider suddenly takes 5 seconds.', teach: 'Timeouts and retries',
        predict: ['Payments are slow. What happens to the catalog?', ['Nothing', 'It goes down: threads wait on payments', 'It gets faster'], 1, 'A slow dependency ties up threads.'],
        lesson: 'Failing fast saves strength for those you can answer.', real: 'Classic outages start with one slow partner.',
        hints: ['How many seconds does the server wait for payment?', 'Short timeout, no back-to-back retries.', 'Timeout 1 s, retries 0 (or with a pause).'],
        adr: ['Short timeout', ['catalog survives'], ['payments fail during the incident']] },
      zone: { title: 'Zone goes dark', story: 'Everything lives in zone B. At 60 s it gets switched off.', teach: 'Two zones and headroom',
        predict: ['Servers in two zones. Enough?', ['Yes', 'No, if the database is in one or there’s no headroom', 'Need three'], 1, 'A chain is as strong as its weakest link.'],
        lesson: 'Reliability is a property of the whole chain.', real: 'One data center failing regularly takes down “reliable” services.',
        hints: ['What stays alive?', 'Second pool in zone A and database in two zones.', 'Pools ×4 in A and B, database M “two zones”.'],
        adr: ['Two zones', ['survive a zone failure'], ['database ×2 price', 'headroom sits idle']] },
      health: { title: 'Health checks', story: 'One pool hangs twice. The load balancer can’t tell.', teach: 'Health checks',
        predict: ['Half the servers hung. What happens?', ['It’ll figure it out', 'It keeps sending them requests', 'They’ll wait'], 1, 'Without checks it can’t see.'],
        lesson: 'You can’t fix what you can’t see.', real: 'Health checks are the first thing people set up.',
        hints: ['How does the load balancer learn about a hang?', 'Health checks.', 'Turn on checks, 4 machines for the first pool.'],
        adr: ['Health checks', ['the dead get no traffic'], ['a couple of seconds to detect']] },
      cfo: { title: 'Call from finance', story: 'The bill is huge. Cut it by more than half.', teach: 'Pay for what you need',
        predict: ['Where to start?', ['Remove everything', 'Find idle and extra work', 'Nothing'], 1, 'Idle first.'],
        lesson: 'Over-insuring is a mistake too, just an expensive one.', real: 'Cloud bills are the second pain after outages.',
        hints: ['What sits idle?', 'Longer cache, fewer machines, smaller database.', 'Servers M ×4, cache 4 GB for 1 h, database S.'],
        adr: ['Cut the extras', ['cheaper'], ['less headroom for surprises']] },
      monitoring: { title: 'Flying blind', story: 'One of three pools can’t cope. Which one — you can’t see.', teach: 'Monitoring',
        predict: ['How to find the weak pool?', ['Add to all', 'Turn on monitoring and look', 'Guess'], 1, 'See first, then fix.'],
        lesson: 'You can’t fix what you don’t measure.', real: 'The first thing done in a new system is metrics.',
        hints: ['Can you see the load?', 'Monitoring.', 'Monitoring + 3 machines for the weak pool.'],
        adr: ['Metrics', ['bottleneck is visible'], ['cost money']] },
      logging: { title: 'Where’s the bug?', story: 'Errors pour in after a release. Four services.', teach: 'Logs',
        predict: ['How to tell which service broke?', ['Roll back everything', 'Check the logs', 'Wait'], 1, 'Logs tell where and what.'],
        lesson: 'Logs let you know instead of guess. But debug is expensive.', real: 'Log storage is a notable line on the bill.',
        hints: ['Can you see who’s failing?', 'Logs at info, then roll back the right service.', 'Logs info; pause; “Roll back version” on the broken one.'],
        adr: ['Info logs', ['error source visible'], ['debug will bankrupt you']] },
      tracing: { title: 'Where time goes', story: 'Requests are slow, but all servers are cold.', teach: 'Tracing',
        predict: ['Servers idle, yet slow. Why?', ['Need more servers', 'Time goes to waiting on something', 'Network'], 1, 'Load and latency are different things.'],
        lesson: 'Metrics show where it’s hot. Traces show where it waits.', real: 'Tracing finds a slow neighbor in minutes.',
        hints: ['Which partner is slow?', 'Tracing, then cache in front of the slow one.', 'Tracing 10% and cache in front of the third partner.'],
        adr: ['Sampled tracing', ['slow step is visible'], ['100% recording is expensive']] },
      loadtest: { title: 'Before launch', story: 'Launch in a week, expecting 4× more people.', teach: 'Load testing',
        predict: ['How to know if it holds?', ['Hope', 'Load test', 'Buy everything'], 1, 'Find the limit before launch.'],
        lesson: 'Find the limit before users do.', real: 'Before big sales, companies run load tests.',
        hints: ['Where will it break first?', 'Press “Load test”.', 'Cache + database M, then test.'],
        adr: ['Test before launch', ['no surprises'], ['time and a test bench']] },
      testing: { title: 'Bad release', story: 'New version has a bug: half the requests fail.', teach: 'Tests and canary',
        predict: ['What saves you best?', ['Tests only', 'Tests plus canary rollout', 'Nothing'], 1, 'Tests catch some, canary catches the rest.'],
        lesson: 'Tests reduce risk, canary reduces damage.', real: 'Big services roll out to 1% and watch.',
        hints: ['What if tests miss the bug?', 'Canary + monitoring for rollback.', 'Unit tests, canary rollout, monitoring.'],
        adr: ['Canary rollout', ['a bug hits few'], ['slower rollout']] },
      twelve: { title: '12 factors', story: 'The app keeps sessions in memory, config in the image, logs in a file.', teach: '12-factor',
        predict: ['The app must scale. What’s in the way?', ['Nothing', 'State inside the process', 'The language'], 1, 'Processes should be disposable.'],
        lesson: 'A stateless process can be cloned and killed.', real: '12-factor is the basis of cloud apps.',
        hints: ['What does a user lose if they hit another server?', 'Sessions to cache, config to env, logs to a stream.', 'Sessions: in cache; config: in env; logs: to stream; autoscale.'],
        adr: ['Stateless processes', ['painless scaling and restarts'], ['needs external storage']] },
      k8s1: { title: 'Zero-downtime rollout', story: 'Two new-version rollouts per run.', teach: 'Pods, readiness, updates',
        predict: ['How to update with no downtime?', ['Recreate everything', 'Rolling, with a readiness probe', 'At night'], 1, 'A new pod gets traffic once ready.'],
        lesson: 'Traffic goes only to ready pods.', real: 'Rolling update + readiness probe is the Kubernetes standard.',
        hints: ['What gets traffic while a pod starts?', 'Readiness probe and rolling update.', 'Readiness: on, update: rolling.'],
        adr: ['Rolling + readiness', ['zero downtime'], ['slower rollout']] },
      k8s2: { title: 'Pods are cramped', story: 'Traffic grows 8×. Pods exist, room doesn’t.', teach: 'HPA and cluster autoscaling',
        predict: ['HPA wants more pods, but nodes are full. What happens?', ['They start', 'They wait for room', 'All crash'], 1, 'Pods need CPU on nodes.'],
        lesson: 'Pod scaling hits the cluster size.', real: 'Cluster Autoscaler adds nodes when pods wait.',
        hints: ['Enough nodes at peak?', 'HPA + cluster autoscaler.', 'HPA 2–12 and “Cluster autoscaler”.'],
        adr: ['HPA + Cluster Autoscaler', ['grows on its own'], ['a node doesn’t start instantly']] },
      k8s3: { title: 'Nodes go away', story: 'First a node fails, then a planned upgrade of all nodes.', teach: 'Spreading across nodes and PDB',
        predict: ['All pods on one node. It failed. What happens?', ['Nothing', 'Full downtime', 'A bit slower'], 1, 'Don’t put all eggs in one basket.'],
        lesson: 'Spread pods out and don’t evict them all at once.', real: 'Cluster upgrades without PDB are a common outage cause.',
        hints: ['Where do pods live, and how are they evicted?', 'Spread across nodes and PDB.', 'Spread: on, PDB: on, 8 pods.'],
        adr: ['Anti-affinity + PDB', ['survive failure and upgrade'], ['needs spare pods']] },
      k8s4: { title: 'Noisy neighbor', story: 'Reports on the same nodes suddenly eat all the CPU.', teach: 'Resource limits',
        predict: ['Why is the API slow with the same traffic?', ['Network', 'Neighbors without limits ate the CPU', 'Database'], 1, 'Without limits a neighbor takes it all.'],
        lesson: 'Limits protect neighbors from each other.', real: 'Requests and limits are basic cluster hygiene.',
        hints: ['Who else lives on the nodes?', 'Limits on reports.', 'On the “reports” Deployment, turn on CPU limits.'],
        adr: ['CPU limits', ['neighbors don’t interfere'], ['reports take longer']] },
      sockets: { title: 'Chat for 30,000', story: '30,000 people in chat at once. Then — a restart.', teach: 'WebSockets',
        predict: ['After a restart 30,000 clients reconnect at once. What happens?', ['Nothing', 'An avalanche, the server chokes', 'Instant reconnect'], 1, 'Everyone knocks at once.'],
        lesson: 'Persistent connections mean memory, a bus between instances and careful restarts.', real: 'Reconnect storms have taken down big chats and games.',
        hints: ['Is one instance enough? How do messages reach neighbors?', 'More instances, a broker bus, pause and graceful drain.', 'Sockets ×4, link to broker, pause and graceful drain.'],
        adr: ['Bus + graceful drain', ['messages arrive', 'no avalanche'], ['one more component']] },
      certs: { title: 'Certificate expiring', story: 'The HTTPS certificate is renewed by hand. It expires in 50 seconds.', teach: 'Certificates',
        predict: ['What happens when the certificate expires?', ['Nothing', 'Browsers stop opening the site', 'Slower'], 1, 'No certificate, no trust.'],
        lesson: 'Anything done by hand once a year will one day be forgotten.', real: 'Expired certificates have taken down even giants.',
        hints: ['Who will renew the certificate?', 'Auto-renewal.', 'Certificate: auto.'],
        adr: ['Automatic certificates', ['you won’t forget'], ['needs setup']] },
      security: { title: 'Attack', story: 'Bots, a leaked password and an open-database scanner.', teach: 'Security',
        predict: ['The DB password leaked from code. What saves you?', ['Nothing', 'Secrets in a vault with rotation', 'A complex password'], 1, 'Secrets don’t belong in code.'],
        lesson: 'Security is mostly settings, not hardware.', real: 'Open databases and leaked keys are the most common breaches.',
        hints: ['Which doors are open?', 'Firewall, secrets vault, close the database.', 'Firewall (medium+loose), Secrets, database: not from internet.'],
        adr: ['Defense in depth', ['attacks die at the door'], ['a bit pricier']] },
      vpn: { title: 'Legacy ERP', story: 'Orders must be written to a private ERP in the office.', teach: 'VPN',
        predict: ['Can you reach a private system over the internet?', ['Yes', 'No, through a tunnel', 'Only at night'], 1, 'Private goes through a secure channel.'],
        lesson: 'Private goes through a tunnel, tunnels come in pairs.', real: 'Site-to-site VPN with two tunnels is the standard.',
        hints: ['How to reach the ERP safely?', 'VPN, ideally two tunnels.', 'Servers → VPN (2 tunnels) → ERP.'],
        adr: ['VPN with two tunnels', ['private and reliable'], ['double tunnel price']] },
      multiregion: { title: 'Two regions', story: 'Half the people are in another region. Region 1 will go down.', teach: 'Multi-region',
        predict: ['A region is down. What do you need so people don’t notice?', ['Nothing', 'Second region, DNS and a data copy', 'More servers'], 1, 'You need somewhere to switch to, and the data.'],
        lesson: 'Multi-region is mostly about data.', real: 'A sync copy loses nothing, an async one is faster.',
        hints: ['Where will people go, and where will data come from?', 'DNS, a stack in the second region, a database copy.', 'DNS → load balancers in R1 and R2 → servers; database with a copy.'],
        adr: ['Active second region', ['survive a region'], ['×2 price', 'sync writes are slower']] },
      multicloud: { title: 'Cloud down', story: 'Two regions — but both in one cloud. The whole cloud goes down.', teach: 'Multi-cloud',
        predict: ['Do two regions of one cloud save you from a cloud outage?', ['Yes', 'No', 'Sometimes'], 1, 'Shared provider — shared point of failure.'],
        lesson: 'Multi-cloud saves you from a provider outage, but cross-cloud traffic costs money.', real: 'Many choose multi-region — multi-cloud is expensive.',
        hints: ['What do the two regions share?', 'Second region in another cloud.', 'Region 2: cloud 2.'],
        adr: ['Second cloud', ['survive the provider'], ['paid traffic', 'two platforms']] },
      monolith: { title: 'Start with a monolith', story: 'A tiny startup, yet split into six services.', teach: 'A monolith is fine',
        predict: ['200 requests per second and 6 services. What’s better?', ['More services', 'Merge into one', 'Nothing'], 1, 'Every service is overhead.'],
        lesson: 'Start with a monolith. Split when it hurts.', real: 'Many successful products run on a monolith for years.',
        hints: ['What does each separate service cost?', 'All modules into one group.', 'Group A for all, 2 instances.'],
        adr: ['Monolith', ['cheap', 'fast'], ['shared failure', 'scales as a whole']] },
      modular: { title: 'Modular monolith', story: 'A heavy report chokes the whole monolith. And modules share tables.', teach: 'Boundaries inside',
        predict: ['The report ate all capacity. How to protect the rest without splitting the monolith?', ['No way', 'Bulkheads inside the process', 'New server'], 1, 'Each module gets its own share.'],
        lesson: 'Modules with clear boundaries make a monolith easy to split.', real: 'A modular monolith is a common pick over microservices.',
        hints: ['How do modules get in each other’s way?', 'Bulkheads and no shared tables.', 'Bulkheads: on; delete “shared DB” links.'],
        adr: ['Modular monolith', ['isolation without network calls'], ['still one release']] },
      strangler: { title: 'Smart split', story: 'Search eats half the monolith.', teach: 'Pull out the hot part',
        predict: ['What’s cheaper?', ['Clone the monolith', 'Pull out only search', 'Split everything'], 1, 'Scale what’s hot.'],
        lesson: 'Cut where it hurts, not where it’s trendy.', real: 'Strangler fig: carve out piece by piece.',
        hints: ['What’s hottest?', 'Search into its own group.', 'Search: group B ×6, monolith ×5.'],
        adr: ['Pull out search', ['cheap scaling'], ['one more service']] },
      distmono: { title: 'Distributed monolith', story: 'There are services, but all wait on each other and share a database.', teach: 'Coupling',
        predict: ['Notifications went down. What happens to orders?', ['Nothing', 'They go down too', 'They speed up'], 1, 'Sync waiting ties fates together.'],
        lesson: 'Microservices with sync chains and a shared database are a monolith, only worse.', real: 'The most common trouble of “microservice” systems.',
        hints: ['Who are orders waiting on for nothing?', 'Notifications and stats via events, no shared tables.', 'notify, stats — event; billing — command; remove “shared DB”.'],
        adr: ['Events instead of waiting', ['failures don’t cascade'], ['data a bit later']] },
      mshell: { title: 'Microservice hell', story: 'Twelve services for six hundred requests.', teach: 'Too fine-grained',
        predict: ['What’s wrong with 12 services?', ['All good', 'Expensive, many hops', 'Too few'], 1, 'Every hop and every service costs.'],
        lesson: 'A service is a unit of independence, not a function.', real: 'Many companies merge services back.',
        hints: ['Which modules always go together?', 'Merge by meaning, secondary stuff via events.', 'web+auth+user; feed; search; avatar and tz — via events.'],
        adr: ['Coarser by meaning', ['cheaper and faster'], ['more team per service']] },
      dddstrat: { title: 'Context boundaries', story: 'Sales and support chat with the wrong parties.', teach: 'DDD: strategy',
        predict: ['Where to draw a service boundary?', ['By tables', 'Where there’s little talk', 'By teams'], 1, 'Chatty things go together.'],
        lesson: 'A boundary goes where talk is rare and language is its own.', real: 'Bounded context is the core of DDD.',
        hints: ['Who chats with whom the most?', 'Pricing to sales, tickets to support, ACL to customer.', 'pricing→A, ticket→C, ACL on links to customer.'],
        adr: ['Contexts + ACL', ['little network chatter', 'changes don’t break things'], ['model translation']] },
      dddtact: { title: 'Aggregates', story: 'Order, its lines, product and stock — all in one transaction.', teach: 'DDD: tactics',
        predict: ['Every order needs the product. Put it in the order aggregate?', ['Yes', 'No: you get a lock queue', 'Doesn’t matter'], 1, 'A shared hot object is a bottleneck.'],
        lesson: 'An aggregate is the smallest integrity boundary.', real: 'Big aggregates are a common cause of locking.',
        hints: ['What must change atomically?', 'Order with lines together, product apart, stock via event.', 'line→A, product→B, stock→C via event.'],
        adr: ['Small aggregates', ['no locking'], ['consistency between them comes later']] },
      cmdevt: { title: 'Commands and events', story: 'Payments, emails, stats need the order — and soon loyalty.', teach: 'Commands and events',
        predict: ['Stats went down. Should the order fail?', ['Yes', 'No: an event is enough for it', 'Sometimes'], 1, 'FYI means no waiting.'],
        lesson: 'Command — “do it” to one. Event — “it happened” to all.', real: 'Event-driven architecture lowers coupling.',
        hints: ['Whom should the order tell “do it”, and whom “it happened”?', 'Payment is a command, the rest are events.', 'pay: command; mail, stats, loyalty: event; orders ×3.'],
        adr: ['Events for FYI', ['new subscribers without rework'], ['harder to track']] },
      saga: { title: 'Saga', story: 'An order reserves stock, then pays, then ships. Payment sometimes fails.', teach: 'Processes and compensations',
        predict: ['Payment declined after the reservation. What about the reservation?', ['Released on its own', 'Stuck, unless someone undoes it', 'Doesn’t matter'], 1, 'Someone has to undo it.'],
        lesson: 'A long process is steps and compensations.', real: 'Saga is the standard for distributed processes.',
        hints: ['Who releases the reservation if payment fails?', 'Async steps and a saga.', 'Links as commands, add a Saga.'],
        adr: ['Saga orchestrator', ['no stuck reservations', 'survive failures'], ['more complex logic']] },
      friday: { title: 'Black Friday', story: 'Surge, bots, zone outage — all in one Friday.', teach: 'Everything at once',
        predict: ['Where to start?', ['The database', 'The entry: cut junk and answer from the edge', 'Monitoring'], 1, 'Less junk inside — less to build.'],
        lesson: 'Design from the entry inward.', real: 'Sales are the big exam for shops.',
        hints: ['What to stop at the door?', 'CDN and firewall, two zones, a queue.', 'CDN → Firewall → Load balancer → Servers in A and B + Storage, cache, database “two zones”, queue, monitoring.'],
        adr: ['Layered defense', ['withstands everything'], ['expensive']] },
    },
  };
  return U.TXT.en;
});
